##
# GitHub workflow.
##

name: 'CI Deployment' # <https://o5p.me/QsaIUU>
run-name: 'CI Deployment by @${{github.actor}}'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19.1.0, 20.5.1]

    runs-on: ${{matrix.os}}
    environment: ci # Repo CI env.

    permissions: # GitHub token permissions.
      contents: read

    env: # Supplied by action w/ permissions above.
      USER_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Supplied by org-wide action secrets.
      USER_NPM_TOKEN: ${{secrets.USER_NPM_TOKEN}}

      # Supplied by repo environment secrets.
      USER_DOTENV_KEY_MAIN: ${{secrets.USER_DOTENV_KEY_MAIN}}
      USER_DOTENV_KEY_CI: ${{secrets.USER_DOTENV_KEY_CI}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check Repo Contents
        shell: bash # Explicitly.
        run: |
          if [[ -d ./dev/.files ]]; then
              echo 'dev_files=true' >> $GITHUB_OUTPUT
          fi;
        id: check # For conditionals below.

      - name: Setup Node v${{matrix.node-version}}
        if: steps.check.outputs.dev_files == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm # Cache NPM dependencies.

      - name: Install Project
        if: steps.check.outputs.dev_files == 'true'
        shell: bash # Explicitly.
        run: |
          npx @clevercanyon/madrun install project --mode=ci;
