##
# GitHub workflow.
##

name: "CI Deployment" # <https://o5p.me/QsaIUU>
run-name: "CI Deployment by @${{github.actor}}"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19.2.0, 19.4.0]

    runs-on: ${{matrix.os}}

    permissions: # GitHub token.
      contents: read

    environment: ci # Repo CI environment.
    env: # Supplied by action w/ permissions above.
      USER_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Supplied by org-wide action secrets.
      USER_NPM_TOKEN: ${{secrets.USER_NPM_TOKEN}}

      # Supplied by repo environment secrets.
      USER_DOTENV_KEY_MAIN: ${{secrets.USER_DOTENV_KEY_MAIN}}
      USER_DOTENV_KEY_CI: ${{secrets.USER_DOTENV_KEY_CI}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node v${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm # Cache NPM dependencies.

      - name: Install Project
        shell: bash # Bash explicitly.
        run: |
          if [[ -d ./dev/.files ]]; then
              npx @clevercanyon/madrun install:project --mode=ci;
          fi;
